<?php


namespace App\JavaH2H\Reformat;

class Internet extends BaseReformat implements ReformatInterace
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->data = collect($this->data)
            ->whereIn('provider_sub', ['INTERNET'])
            ->values();
    }
}
