<?php


namespace App\JavaH2H\Reformat;


class Pulsa extends BaseReformat implements ReformatInterace
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->data = collect($this->data)
            ->whereIn('provider_sub', ['REGULER'])
            ->values();
    }
}
